import 'dart:io';

import 'package:path/path.dart' as p;

import 'models.dart';

/// Generate or merge `test/glint_screenshots_test.dart` with real widget builders.
class ScreensTestCodegen {
  ScreensTestCodegen({
    required this.projectRoot,
    this.appName = 'MyApp',
    this.tagline,
    this.testRelativePath = 'test/glint_screenshots_test.dart',
  });

  final String projectRoot;
  final String appName;
  final String? tagline;
  final String testRelativePath;

  File get testFile => File(p.join(projectRoot, testRelativePath));

  /// Write a full test file from [screens].
  Future<File> writeFull(List<DiscoveredScreen> screens) async {
    final file = testFile;
    await file.parent.create(recursive: true);
    await file.writeAsString(generateFullSource(screens));
    return file;
  }

  /// Merge new screens into an existing test file when possible; otherwise rewrite.
  Future<File> mergeOrWrite(List<DiscoveredScreen> screens) async {
    final file = testFile;
    if (!file.existsSync()) {
      return writeFull(screens);
    }
    final existing = await file.readAsString();
    final existingNames = _existingRuleNames(existing);
    final toAdd = screens.where((s) => !existingNames.contains(s.name)).toList();
    if (toAdd.isEmpty) {
      return file;
    }

    // Prefer append before closing of rules: ];  inside glintScreenshots
    final insertAt = existing.lastIndexOf('],');
    if (insertAt == -1 || !existing.contains('glintScreenshots')) {
      return writeFull(screens);
    }

    final importsToAdd = <String>{};
    for (final s in toAdd) {
      final line = "import '${s.importUri}';";
      if (!existing.contains(s.importUri)) {
        importsToAdd.add(line);
      }
    }

    var next = existing;
    if (importsToAdd.isNotEmpty) {
      final firstImport = next.indexOf('import ');
      if (firstImport >= 0) {
        next = next.replaceFirst(
          'import ',
          '${importsToAdd.join('\n')}\nimport ',
        );
      } else {
        next = '${importsToAdd.join('\n')}\n$next';
      }
    }

    final rulesChunk = StringBuffer();
    for (final s in toAdd) {
      rulesChunk.writeln(_ruleSnippet(s));
    }

    next = next.replaceRange(insertAt, insertAt, '${rulesChunk.toString()}    ');
    await file.writeAsString(next);
    return file;
  }

  String generateFullSource(List<DiscoveredScreen> screens) {
    final imports = <String>{
      "import 'package:flutter/material.dart';",
      "import 'package:glint_capture/glint_capture.dart';",
    };
    for (final s in screens) {
      imports.add("import '${s.importUri}';");
    }

    final rules = StringBuffer();
    for (final s in screens) {
      rules.writeln(_ruleSnippet(s));
    }

    final taglineLine =
        tagline == null ? '' : "\n    tagline: ${_dartString(tagline!)},";

    return '''${imports.join('\n')}

/// Auto-generated by `glint discover` / `glint capture --auto`.
/// Uses **real** app widgets only — edit freely, then run `glint capture`.
/// Soft launch: one device (pixel9) for clean Glint Web frame mapping.
void main() {
  glintScreenshots(
    appName: ${_dartString(appName)},$taglineLine
    devices: [GLINTDevice.pixel9],
    rules: [
${rules.toString()}    ],
  );
}
''';
  }

  static String _ruleSnippet(DiscoveredScreen s) {
    final ctor = s.hasConstConstructor
        ? 'const ${s.className}()'
        : '${s.className}()';
    return '''      GLINTRule.screen(
        name: '${s.name}',
        builder: (context) => $ctor,
      ),
''';
  }

  static Set<String> _existingRuleNames(String source) {
    final names = <String>{};
    for (final m in RegExp(r"name:\s*'([^']+)'").allMatches(source)) {
      names.add(m.group(1)!);
    }
    for (final m in RegExp(r'name:\s*"([^"]+)"').allMatches(source)) {
      names.add(m.group(1)!);
    }
    return names;
  }

  static String _dartString(String value) {
    final escaped = value
        .replaceAll(r'\', r'\\')
        .replaceAll("'", r"\'");
    return "'$escaped'";
  }
}
